---
- name: Create read-replica
  local_action:
    module: rds
    command: replicate
    instance_name: db-read-replica
    source_instance: sharath-nclouds
    region: us-east-1
    wait: yes
    wait_timeout: 1200
   
- rds:
    command: facts
    instance_name: db-read-replica
    region: us-east-1
  register: newfacts

- local_action: copy content={{ newfacts }} dest=./facts/facts

